# yfinance Package Usage

In [2]:
import yfinance as yf

wow = yf.Ticker("WOW.AX")
print(wow)

yfinance.Ticker object <WOW.AX>

In [11]:
wow.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1993-08-02,1.083447,1.083447,1.083447,1.083447,0,0.0,0.0
1993-08-03,1.083447,1.083447,1.083447,1.083447,0,0.0,0.0
1993-08-04,1.083447,1.083447,1.083447,1.083447,0,0.0,0.0
1993-08-05,1.083447,1.083447,1.083447,1.083447,0,0.0,0.0
1993-08-06,1.083447,1.083447,1.083447,1.083447,0,0.0,0.0
...,...,...,...,...,...,...,...
2021-06-16,43.520000,44.060001,43.389999,43.700001,2751890,0.0,0.0
2021-06-17,43.779999,43.779999,43.150002,43.349998,4539024,0.0,0.0
2021-06-18,43.480000,43.580002,42.549999,42.669998,5834452,0.0,0.0
2021-06-21,42.549999,43.160000,42.240002,43.020000,4494154,0.0,0.0
2021-06-22,43.200001,43.740002,43.169998,43.305000,1741638,0.0,0.0

In [6]:
print(type(wow.balance_sheet))
wow.balance_sheet

<class 'pandas.core.frame.DataFrame'>

,2020-06-28,2019-06-30,2018-06-24,2017-06-25
Intangible Assets,3.521000e+09,3.576000e+09,2.310000e+09,2.317000e+09
Total Liab,2.944000e+10,1.343200e+10,1.254200e+10,1.316700e+10
Total Stockholder Equity,8.742000e+09,1.010100e+10,1.048100e+10,9.526000e+09
Minority Interest,2.900000e+08,3.830000e+08,3.680000e+08,3.500000e+08
Other Current Liab,8.130000e+08,8.100000e+08,8.230000e+08,1.169000e+09
Total Assets,3.847200e+10,2.391600e+10,2.339100e+10,2.304300e+10
Common Stock,6.197000e+09,6.033000e+09,6.201000e+09,5.719000e+09
Other Current Assets,8.830000e+08,2.700000e+08,8.740000e+08,1.260000e+09
Retained Earnings,2.329000e+09,3.783000e+09,4.073000e+09,3.554000e+09
Other Liab,1.177000e+09,1.692000e+09,1.314000e+09,1.438000e+09
Good Will,4.196000e+09,4.217000e+09,4.155000e+09,4.216000e+09
Treasury Stock,2.160000e+08,2.850000e+08,2.070000e+08,2.530000e+08
Other Assets,1.732000e+09,1.482000e+09,7.300000e+08,8.330000e+08
Cash,2.068000e+09,1.066000e+09,1.273000e+09,9.090000e+08
Total Current Liabilities,1.319100e+10,8.885000e+09,9.029000e+09,8.952000e+09
Deferred Long Term Asset Charges,1.327000e+09,7.360000e+08,2.710000e+08,3.720000e+08
Short Long Term Debt,1.807000e+09,NaN,5.000000e+08,NaN
Other Stockholder Equity,2.160000e+08,2.850000e+08,2.070000e+08,2.530000e+08
Property Plant Equipment,2.080400e+10,8.252000e+09,9.026000e+09,8.438000e+09
Total Current Assets,8.125000e+09,6.298000e+09,7.014000e+09,7.121000e+09
Long Term Investments,9.400000e+07,9.100000e+07,1.560000e+08,1.180000e+08
Net Tangible Assets,1.025000e+09,2.308000e+09,4.016000e+09,2.993000e+09
Net Receivables,5.480000e+08,4.700000e+08,4.200000e+08,4.110000e+08
Long Term Debt,1.904000e+09,2.852000e+09,2.199000e+09,2.775000e+09
Inventory,4.434000e+09,4.280000e+09,4.233000e+09,4.207000e+09
Accounts Payable,5.843000e+09,5.219000e+09,5.149000e+09,5.195000e+09
Short Term Investments,NaN,4.500000e+07,NaN,NaN